[theme]
primaryColor = "#0088CC"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#57595A"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
